import type { Metadata } from "next";
import { Oswald, Source_Serif_4} from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["500", "700"]
});

const source_Serif_4 = Source_Serif_4({
  variable: "--font-source_Serif_4",
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Road to Worlds 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${oswald.variable} ${source_Serif_4.variable} antialiased bg-[#0A1926]`}
      >
        {children}
      </body>
    </html>
  );
}
